package com.examples.grant_categories;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class GrantApplication implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public GrantApplication() {
    }




}